version: '3.1'
services:
  pgdb:
    image: postgres:10.7
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    volumes:
      - ~/data/todolist-db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped